{"uuid": "1055da14-adcf-4c91-b3ca-0bbc4013e62b", "children": ["df86ebc0-5fcb-4be7-9160-155c2518793a", "3b80f475-e408-44a0-8000-812efe1f99b3", "d505a6c3-a6eb-41d0-87c4-e4d60de8c55d", "40f3aaf1-6f06-4b85-a46f-ce0549e634e2", "b14989cf-86a8-4dca-87c3-f7dc573873bc", "cdff9102-5b0a-465b-84a1-f8415fb393b8", "2609958d-850d-48f3-9001-10c776cb2e29", "e1980a3d-fbe9-4be7-85de-92be915b1fb1", "89b5fb25-6af5-4333-8da8-f48088cd2aff"], "befores": [{"name": "project_session_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0120D343+3134275]\n\tOrdinal0 [0x010FA131+2007345]\n\tOrdinal0 [0x00F9AEC8+569032]\n\tOrdinal0 [0x00F1C9B7+51639]\n\tOrdinal0 [0x00F40DFC+200188]\n\tOrdinal0 [0x00F40C1D+199709]\n\tOrdinal0 [0x00F3EB0B+191243]\n\tOrdinal0 [0x00F22E77+77431]\n\tOrdinal0 [0x00F23E3E+81470]\n\tOrdinal0 [0x00F23DC9+81353]\n\tOrdinal0 [0x01110C99+2100377]\n\tGetHandleVerifier [0x0137B71A+1396954]\n\tGetHandleVerifier [0x0137B399+1396057]\n\tGetHandleVerifier [0x013870E6+1444518]\n\tGetHandleVerifier [0x0137BCA8+1398376]\n\tOrdinal0 [0x01107F11+2064145]\n\tOrdinal0 [0x011122AB+2106027]\n\tOrdinal0 [0x011123D1+2106321]\n\tOrdinal0 [0x01124984+2181508]\n\tBaseThreadInitThunk [0x75F86359+25]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7C24+228]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7BF4+180]\n\n", "trace": "  File \"d:\\program files (x86)\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\seleniumweb\\saas\\TestCase\\conftest.py\", line 34, in project_session_login\n    driver = webdriver.Chrome(chromedriver)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 64, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 79, in __init__\n    RemoteWebDriver.__init__(\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 183, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 280, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 349, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 240, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1600684168023, "stop": 1600684170961}], "start": 1600684168023, "stop": 1600684171584}