{"uuid": "6a0eec4d-983b-4c7f-b18a-7e32336af47d", "children": ["4fdeeb47-ff78-4a78-a933-e9bcb3f7c8b3", "7314c2cc-c4a3-470c-88e0-7f23b7971b00", "57517469-d6ff-4dd9-9b9b-9f15cc99fd7d", "b2da95d4-eac0-4833-980d-88fb159d3dbe", "55c560a4-2382-4ec9-a648-bee53fdb894f", "60419c5d-b1cf-40a8-a157-cca812c4775c", "e9ec01a8-5853-4c3c-afb6-d133391e4b68"], "befores": [{"name": "project_session_login", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../img/img_01.png'\n", "trace": "  File \"d:\\program files (x86)\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\seleniumweb\\saas\\TestCase\\conftest.py\", line 39, in project_session_login\n    auth = Auth(driver).auth_all('../img/img_03.png')\n  File \"D:\\seleniumweb\\saas\\Common\\common_auth.py\", line 153, in auth_all\n    self.auth_img()\n  File \"D:\\seleniumweb\\saas\\Common\\common_auth.py\", line 29, in auth_img\n    img_save = Image.open('../img/img_01.png')\n  File \"d:\\program files (x86)\\lib\\site-packages\\PIL\\Image.py\", line 2878, in open\n    fp = builtins.open(filename, \"rb\")\n"}, "start": 1601022852598, "stop": 1601022864434}], "start": 1601022852598, "stop": 1601022865020}