{"uuid": "466a0903-f51b-422b-b182-4a231f2ce8e0", "children": ["71ebd6fc-8076-41cf-b73d-0b134149628e", "649f85a2-b578-44fa-9353-a8b71c9f31fa", "5b946e63-7d3f-4e2a-b172-1ad6738d4f47", "899ee91c-f7be-4c78-9f69-53d653c2603a", "7c9639f1-f5bf-4f95-84ef-5e964a79a846", "c631800f-8cf9-4356-8d7f-fdf96eaaa9ff", "d22384a9-abe7-4340-8154-fe0d77f0604c", "fbe56794-08a5-45ea-a61d-331af1868af2", "de117a27-62fd-4023-a583-77c75c5e62b2", "db640c57-fe12-4eac-9821-b4d92b9dec4b", "775c2d24-58d0-4882-80df-4bcca9706370", "61b8c13c-1dbb-4e9f-92b2-6100d262a63d", "a690fa0a-9767-4816-b1dd-bd85911d47d6", "3383e5c5-8c8b-41ab-8ae9-18725cc6ef50", "759e4aac-3f6b-407a-983a-b55763337a45"], "befores": [{"name": "session_login", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../img/img_01.png'\n", "trace": "  File \"d:\\program files (x86)\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\seleniumweb\\saas\\TestCase\\lab_test\\conftest.py\", line 22, in session_login\n    auth = Auth(driver).auth_all('../img/img_03.png')\n  File \"D:\\seleniumweb\\saas\\Common\\common_auth.py\", line 153, in auth_all\n    self.auth_img()\n  File \"D:\\seleniumweb\\saas\\Common\\common_auth.py\", line 29, in auth_img\n    img_save = Image.open('../img/img_01.png')\n  File \"d:\\program files (x86)\\lib\\site-packages\\PIL\\Image.py\", line 2878, in open\n    fp = builtins.open(filename, \"rb\")\n"}, "start": 1601022641689, "stop": 1601022651873}], "start": 1601022641689, "stop": 1601022664494}