{"uuid": "3f13e2bc-5eab-4bd0-a9a2-e4d5bb0b3c8a", "children": ["75ea3ed3-8757-4543-ac64-723522bd1092", "611dbea3-fd84-446b-ab3e-c861963ad888", "2ac1242b-d2a1-4deb-997d-66d44bb59966"], "befores": [{"name": "project_session_start", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0120D343+3134275]\n\tOrdinal0 [0x010FA131+2007345]\n\tOrdinal0 [0x00F9AEC8+569032]\n\tOrdinal0 [0x00F1C9B7+51639]\n\tOrdinal0 [0x00F40DFC+200188]\n\tOrdinal0 [0x00F40C1D+199709]\n\tOrdinal0 [0x00F3EB0B+191243]\n\tOrdinal0 [0x00F22E77+77431]\n\tOrdinal0 [0x00F23E3E+81470]\n\tOrdinal0 [0x00F23DC9+81353]\n\tOrdinal0 [0x01110C99+2100377]\n\tGetHandleVerifier [0x0137B71A+1396954]\n\tGetHandleVerifier [0x0137B399+1396057]\n\tGetHandleVerifier [0x013870E6+1444518]\n\tGetHandleVerifier [0x0137BCA8+1398376]\n\tOrdinal0 [0x01107F11+2064145]\n\tOrdinal0 [0x011122AB+2106027]\n\tOrdinal0 [0x011123D1+2106321]\n\tOrdinal0 [0x01124984+2181508]\n\tBaseThreadInitThunk [0x75F86359+25]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7C24+228]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7BF4+180]\n\n", "trace": "  File \"d:\\program files (x86)\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\seleniumweb\\saas\\TestCase\\conftest.py\", line 20, in project_session_start\n    driver = webdriver.Chrome(chromedriver)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 64, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 79, in __init__\n    RemoteWebDriver.__init__(\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 183, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 280, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 349, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 240, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1600684164706, "stop": 1600684167642}], "start": 1600684164706, "stop": 1600684171589}