{"uuid": "b82fa755-0561-4810-bc3b-163b1f868fe5", "children": ["8194e539-0cfb-421d-b502-d081ab5108a4", "1bac0662-6262-47f0-8d9f-d84590156f9f", "cc80a868-71a7-438c-8e22-5922706bee66", "a6dc1e20-70bf-449f-af24-17674c862fc4", "2bb508c9-603d-4157-a85c-2b06ca274b3c", "572c1715-cb91-4123-9ef3-5b6481059494", "824f8c9f-c148-470a-9cbd-60fbd2ed081f"], "befores": [{"name": "start_module", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=57560): Max retries exceeded with url: /session/ad17877d6b96d2d026d70227707d2b3c/elements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x041068B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))\n", "trace": "  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\seleniumweb\\saas\\TestCase\\test_system\\conftest.py\", line 11, in start_module\n    loc(driver).get_system()\n  File \"D:\\seleniumweb\\saas\\Locators\\SystemLocators\\system_locators.py\", line 10, in get_system\n    self.click_element(self.click_subscribe)\n  File \"D:\\seleniumweb\\saas\\Common\\plugs\\basepage.py\", line 35, in click_element\n    self.get_element(locator).click()\n  File \"D:\\seleniumweb\\saas\\Common\\plugs\\basepage.py\", line 23, in get_element\n    self.wait_vs(locator)\n  File \"D:\\seleniumweb\\saas\\Common\\plugs\\basepage.py\", line 17, in wait_vs\n    WebDriverWait(self.driver, timeout=10, poll_frequency=0.5).until(EC.presence_of_all_elements_located(locator))\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 71, in until\n    value = method(self._driver)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 161, in __call__\n    return _find_elements(driver, self.locator)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 420, in _find_elements\n    return driver.find_elements(*by)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1005, in find_elements\n    return self.execute(Command.FIND_ELEMENTS, {\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\request.py\", line 79, in request\n    return self.request_encode_body(\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\request.py\", line 171, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 336, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 754, in urlopen\n    return self.urlopen(\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 754, in urlopen\n    return self.urlopen(\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 754, in urlopen\n    return self.urlopen(\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 726, in urlopen\n    retries = retries.increment(\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 439, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1600676362790, "stop": 1600676389941}], "start": 1600676362790, "stop": 1600676393252}