{"name": "test_10[data0]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../img/img_01.png'", "trace": "@pytest.fixture(scope=\"session\")\n    def session_login():\n        chromedriver = PATH(\"../../software/chromedriver.exe\")\n        os.environ['webdriver.chrome.driver'] = chromedriver\n        global driver\n        driver = webdriver.Chrome(chromedriver)\n        driver.get(LD.get_url['url'])\n        driver.maximize_window()\n        driver.implicitly_wait(20)\n        loc(driver).get_login_click()\n>       auth = Auth(driver).auth_all('../img/img_03.png')\n\nlab_test\\conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\Common\\common_auth.py:153: in auth_all\n    self.auth_img()\n..\\Common\\common_auth.py:29: in auth_img\n    img_save = Image.open('../img/img_01.png')\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nfp = '../img/img_01.png', mode = 'r'\n\n    def open(fp, mode=\"r\"):\n        \"\"\"\n        Opens and identifies the given image file.\n    \n        This is a lazy operation; this function identifies the file, but\n        the file remains open and the actual image data is not read from\n        the file until you try to process the data (or call the\n        :py:meth:`~PIL.Image.Image.load` method).  See\n        :py:func:`~PIL.Image.new`. See :ref:`file-handling`.\n    \n        :param fp: A filename (string), pathlib.Path object or a file object.\n           The file object must implement :py:meth:`~file.read`,\n           :py:meth:`~file.seek`, and :py:meth:`~file.tell` methods,\n           and be opened in binary mode.\n        :param mode: The mode.  If given, this argument must be \"r\".\n        :returns: An :py:class:`~PIL.Image.Image` object.\n        :exception FileNotFoundError: If the file cannot be found.\n        :exception PIL.UnidentifiedImageError: If the image cannot be opened and\n           identified.\n        :exception ValueError: If the ``mode`` is not \"r\", or if a ``StringIO``\n           instance is used for ``fp``.\n        \"\"\"\n    \n        if mode != \"r\":\n            raise ValueError(\"bad mode %r\" % mode)\n        elif isinstance(fp, io.StringIO):\n            raise ValueError(\n                \"StringIO cannot be used to open an image. \"\n                \"Binary data must be used instead.\"\n            )\n    \n        exclusive_fp = False\n        filename = \"\"\n        if isinstance(fp, Path):\n            filename = str(fp.resolve())\n        elif isPath(fp):\n            filename = fp\n    \n        if filename:\n>           fp = builtins.open(filename, \"rb\")\nE           FileNotFoundError: [Errno 2] No such file or directory: '../img/img_01.png'\n\nd:\\program files (x86)\\lib\\site-packages\\PIL\\Image.py:2878: FileNotFoundError"}, "parameters": [{"name": "data", "value": "{'add_cas': '56-36-89-78'}"}], "start": 1601022652915, "stop": 1601022652915, "uuid": "db640c57-fe12-4eac-9821-b4d92b9dec4b", "historyId": "9cf0f423c8d8fa2dec895c154a3198bc", "testCaseId": "f042f6cdfa20a78f2fdb8104ac662891", "fullName": "lab_test.test_system.TestSystem#test_10", "labels": [{"name": "story", "value": "修改耗材"}, {"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "lab_test"}, {"name": "suite", "value": "test_system"}, {"name": "subSuite", "value": "TestSystem"}, {"name": "host", "value": "DESKTOP-BQG3M1K"}, {"name": "thread", "value": "10528-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "lab_test.test_system"}]}