{"uuid": "ce669f98-3a52-4aaf-b181-1509976ce223", "children": ["74421f23-e881-4eb5-ace5-c74b3c1519d5", "b111ca40-7da4-4312-be53-ac42d512ad2a", "a14bc42c-9959-4e24-87cf-6f3f78076e98", "452d0ab0-283b-4034-9cf3-b5aa283e8e87", "9b16f853-107d-4bd4-ad6e-b5f617c4b830", "e3e8e66b-7e35-4076-a7d9-549e90e3945d", "b53e83ce-3b92-4880-80cd-0b2064747277", "d88b688b-bb6a-40d9-a43f-4edb73e44793", "014573d5-97ce-4ee0-b75a-016ba5994380", "ea0255cb-eada-410d-9a0f-19f3894dcd59", "609b7d55-1947-4f72-8628-b40f7bfdeee0", "cef6f53c-9dce-48fa-8c61-23c77f46b71b", "32129112-de30-4d3a-b16a-4544c3789810", "4535c1e3-727a-4665-b8aa-195826f02500", "93c484a2-3a23-483e-a5a0-cfa277d816db"], "befores": [{"name": "session_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0074D343+3134275]\n\tOrdinal0 [0x0063A131+2007345]\n\tOrdinal0 [0x004DAEC8+569032]\n\tOrdinal0 [0x0045C9B7+51639]\n\tOrdinal0 [0x00480DFC+200188]\n\tOrdinal0 [0x00480C1D+199709]\n\tOrdinal0 [0x0047EB0B+191243]\n\tOrdinal0 [0x00462E77+77431]\n\tOrdinal0 [0x00463E3E+81470]\n\tOrdinal0 [0x00463DC9+81353]\n\tOrdinal0 [0x00650C99+2100377]\n\tGetHandleVerifier [0x008BB71A+1396954]\n\tGetHandleVerifier [0x008BB399+1396057]\n\tGetHandleVerifier [0x008C70E6+1444518]\n\tGetHandleVerifier [0x008BBCA8+1398376]\n\tOrdinal0 [0x00647F11+2064145]\n\tOrdinal0 [0x006522AB+2106027]\n\tOrdinal0 [0x006523D1+2106321]\n\tOrdinal0 [0x00664984+2181508]\n\tBaseThreadInitThunk [0x75F86359+25]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7C24+228]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7BF4+180]\n\n", "trace": "  File \"d:\\program files (x86)\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\seleniumweb\\saas\\TestCase\\lab_test\\conftest.py\", line 18, in session_login\n    driver = webdriver.Chrome(chromedriver)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 64, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 79, in __init__\n    RemoteWebDriver.__init__(\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 183, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 280, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 349, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 240, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1601020367826, "stop": 1601020370858}], "start": 1601020367826, "stop": 1601020372177}