{"uuid": "1e8f7364-250e-45ad-a90d-da67f905c99b", "children": ["46524fef-aee7-43ff-98fb-9e07e856f5d9", "73c888bc-1433-4b4b-b824-416e0c34f488", "3f3b2fc9-5f6c-4b7e-98a3-ae75b11523c5", "4ecf259d-0c37-41d2-85d1-38345494bf39", "1b9d82a5-561d-48bc-8229-9af49d13468e", "60dba0ee-ddaa-4dd3-8909-a02d76c394ea", "60bf47d4-132f-4782-a924-2fe8ea0fd125", "eb49b511-dbf5-40d2-88f4-7dcd7df1d61a", "706a6c47-c08e-48a7-9c8e-75dd468af157", "d0639ca5-9d5f-4e25-9b4b-2a262ffe57c8", "b241a9f1-9a88-40c7-8199-aa9efff5b760", "ec6ef08e-86c5-4274-8118-796cc954e95f", "f08aa840-929c-4fed-9cad-2c31df29125b", "7fd48025-877f-4584-80f4-896088e45127", "948608ab-9c0f-49a6-a265-fed4016cfa47"], "befores": [{"name": "session_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0074D343+3134275]\n\tOrdinal0 [0x0063A131+2007345]\n\tOrdinal0 [0x004DAEC8+569032]\n\tOrdinal0 [0x0045C9B7+51639]\n\tOrdinal0 [0x00480DFC+200188]\n\tOrdinal0 [0x00480C1D+199709]\n\tOrdinal0 [0x0047EB0B+191243]\n\tOrdinal0 [0x00462E77+77431]\n\tOrdinal0 [0x00463E3E+81470]\n\tOrdinal0 [0x00463DC9+81353]\n\tOrdinal0 [0x00650C99+2100377]\n\tGetHandleVerifier [0x008BB71A+1396954]\n\tGetHandleVerifier [0x008BB399+1396057]\n\tGetHandleVerifier [0x008C70E6+1444518]\n\tGetHandleVerifier [0x008BBCA8+1398376]\n\tOrdinal0 [0x00647F11+2064145]\n\tOrdinal0 [0x006522AB+2106027]\n\tOrdinal0 [0x006523D1+2106321]\n\tOrdinal0 [0x00664984+2181508]\n\tBaseThreadInitThunk [0x75F86359+25]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7C24+228]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7BF4+180]\n\n", "trace": "  File \"d:\\program files (x86)\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\seleniumweb\\saas\\TestCase\\lab_test\\conftest.py\", line 18, in session_login\n    driver = webdriver.Chrome(chromedriver)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 64, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 79, in __init__\n    RemoteWebDriver.__init__(\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 183, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 280, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 349, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 240, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1601020327178, "stop": 1601020330193}], "start": 1601020327178, "stop": 1601020331533}