{"uuid": "f992dab5-e58c-45d7-a842-8efd87f40687", "children": ["f88c3072-d6a0-4273-ab8b-e619abe877d4", "b2eef5d0-2d49-4d6c-9c2f-55b9720a1202", "b0ce50de-d673-47cf-8c25-f9ea317e6efc", "00f31758-c13e-45c0-93e0-0780cedd31ae", "b0046194-5ef4-4731-aa38-474c7c386dba", "4f43d9a3-7670-4b10-9bab-d84bd035b02e", "339f46e6-2797-4cab-8031-66d38ff9182b", "62f24de8-32ac-4d18-8bab-67469bf208ee", "53c60dd4-6307-4e7d-90bf-5198277e7335", "ac05d952-ca6f-4250-9032-2daa41582c90", "8a68799f-a701-4e99-b8e1-abff00c25c19", "a9f9d806-5c8d-4343-9162-cb771a766dcf", "55f70b09-be35-4be2-8599-2c1a8cce7172", "fe0656b5-1bd8-40ca-a923-ad5f931dff31", "e7deefa4-b0ea-40fe-bf59-96bc5b891fef"], "befores": [{"name": "session_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0074D343+3134275]\n\tOrdinal0 [0x0063A131+2007345]\n\tOrdinal0 [0x004DAEC8+569032]\n\tOrdinal0 [0x0045C9B7+51639]\n\tOrdinal0 [0x00480DFC+200188]\n\tOrdinal0 [0x00480C1D+199709]\n\tOrdinal0 [0x0047EB0B+191243]\n\tOrdinal0 [0x00462E77+77431]\n\tOrdinal0 [0x00463E3E+81470]\n\tOrdinal0 [0x00463DC9+81353]\n\tOrdinal0 [0x00650C99+2100377]\n\tGetHandleVerifier [0x008BB71A+1396954]\n\tGetHandleVerifier [0x008BB399+1396057]\n\tGetHandleVerifier [0x008C70E6+1444518]\n\tGetHandleVerifier [0x008BBCA8+1398376]\n\tOrdinal0 [0x00647F11+2064145]\n\tOrdinal0 [0x006522AB+2106027]\n\tOrdinal0 [0x006523D1+2106321]\n\tOrdinal0 [0x00664984+2181508]\n\tBaseThreadInitThunk [0x75F86359+25]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7C24+228]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7BF4+180]\n\n", "trace": "  File \"d:\\program files (x86)\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\seleniumweb\\saas\\TestCase\\lab_test\\conftest.py\", line 17, in session_login\n    driver = webdriver.Chrome(chromedriver)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 64, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 79, in __init__\n    RemoteWebDriver.__init__(\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 183, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 280, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 349, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 240, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1601021976340, "stop": 1601021979268}], "start": 1601021976340, "stop": 1601021980598}