{"uuid": "6120e758-bfb8-4826-ae36-685ff2c97a35", "children": ["8cdc44c5-a8ef-4efe-abd2-73556ce493f4", "5872f61d-5d1b-4e21-9d3d-d74e6c2a5630", "d8e1930e-6115-422b-88a0-f1c10bbba9f3", "33d28b07-d8c8-444f-a9e3-aa3ec978b212", "0dbc7464-252e-4479-8dfc-2656e2e645e0", "47a9dcaf-ec41-47d2-bcc9-d82d9b415d44", "a1004baf-c97d-4958-993e-32223205c857"], "befores": [{"name": "start_module", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=52215): Max retries exceeded with url: /session/389cfe30f08fd8fd898afd2f8261025c/elements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x042B21D8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))\n", "trace": "  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\seleniumweb\\saas\\TestCase\\test_system\\conftest.py\", line 11, in start_module\n    loc(driver).get_system()\n  File \"D:\\seleniumweb\\saas\\Locators\\SystemLocators\\system_locators.py\", line 10, in get_system\n    self.click_element(self.click_subscribe)\n  File \"D:\\seleniumweb\\saas\\Common\\plugs\\basepage.py\", line 35, in click_element\n    self.get_element(locator).click()\n  File \"D:\\seleniumweb\\saas\\Common\\plugs\\basepage.py\", line 23, in get_element\n    self.wait_vs(locator)\n  File \"D:\\seleniumweb\\saas\\Common\\plugs\\basepage.py\", line 17, in wait_vs\n    WebDriverWait(self.driver, timeout=10, poll_frequency=0.5).until(EC.presence_of_all_elements_located(locator))\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 71, in until\n    value = method(self._driver)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 161, in __call__\n    return _find_elements(driver, self.locator)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 420, in _find_elements\n    return driver.find_elements(*by)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1005, in find_elements\n    return self.execute(Command.FIND_ELEMENTS, {\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\request.py\", line 79, in request\n    return self.request_encode_body(\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\request.py\", line 171, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 336, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 754, in urlopen\n    return self.urlopen(\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 754, in urlopen\n    return self.urlopen(\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 754, in urlopen\n    return self.urlopen(\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 726, in urlopen\n    retries = retries.increment(\n  File \"c:\\users\\user\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 439, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1600673938540, "stop": 1600673962880}], "start": 1600673938540, "stop": 1600673966202}